adminUser:
  password: vault:jx-aps-fighterbrass/adminUser:password
  username: admin
dashboardAuthID: vault:jx-aps-fighterbrass:dashboardAuthID
dashboardAuthOrg: arcalos-dashboard
dashboardAuthSecret: vault:jx-aps-fighterbrass:dashboardAuthSecret
dashboardGrpchost: dex.jx
enableDocker: false
pipelineUser:
  email: jenkins-x@googlegroups.com
  token: vault:jx-aps-fighterbrass/pipelineUser:token
  username: jenkins-x-bot-test
prow:
  hmacToken: vault:jx-aps-fighterbrass/prow:hmacToken
